# Generated by Django 5.0 on 2025-12-01 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('subscription', 'Subscription'), ('specialists', 'Specialists'), ('wellness_plans', 'Wellness Plans'), ('concierge', 'Concierge Services'), ('billing', 'Billing'), ('technical', 'Technical Support')], max_length=20)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='VELORA', max_length=100)),
                ('tagline', models.CharField(default='PREMIUM WELLNESS PLATFORM', max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('support_email', models.EmailField(default='support@velora.com', max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('social_links', models.JSONField(default=dict, help_text='Social media links')),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_specialists', models.PositiveIntegerField(default=0)),
                ('total_wellness_plans', models.PositiveIntegerField(default=0)),
                ('success_stories', models.PositiveIntegerField(default=0)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('new_user_registrations', models.BooleanField(default=True)),
                ('trial_period_days', models.PositiveIntegerField(default=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_specialists', models.PositiveIntegerField(default=1)),
                ('max_wellness_plans', models.PositiveIntegerField(default=1)),
                ('concierge_support', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('ai_coaching', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list, help_text='List of tier-specific features')),
                ('perks', models.JSONField(default=list, help_text='Additional perks and benefits')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('reminder', 'Reminder'), ('achievement', 'Achievement'), ('update', 'Update')], default='info', max_length=20)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Update'), ('plan_created', 'Wellness Plan Created'), ('session_completed', 'Session Completed'), ('specialist_booked', 'Specialist Booked'), ('concierge_request', 'Concierge Request'), ('subscription_change', 'Subscription Change'), ('achievement_unlocked', 'Achievement Unlocked'), ('review_submitted', 'Review Submitted')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('specialists_used', models.PositiveIntegerField(default=0)),
                ('wellness_plans_used', models.PositiveIntegerField(default=0)),
                ('concierge_requests_used', models.PositiveIntegerField(default=0)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.subscriptiontier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
