# Generated by Django 5.0 on 2025-12-01 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialists', '0001_initial'),
        ('wellness_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('scheduling', 'Appointment Scheduling'), ('coordination', 'Specialist Coordination'), ('planning', 'Wellness Plan Management'), ('lifestyle', 'Lifestyle Concierge'), ('emergency', 'Emergency Support'), ('consultation', 'Consultation Services'), ('travel', 'Wellness Travel Planning'), ('nutrition', 'Meal Planning & Delivery'), ('fitness', 'Fitness Equipment & Setup'), ('wellness', 'General Wellness Support')], max_length=20)),
                ('minimum_tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='basic', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_complimentary', models.BooleanField(default=False)),
                ('estimated_completion_time', models.DurationField(blank=True, null=True)),
                ('requires_specialist', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConciergeAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('specializations', models.JSONField(default=list, help_text='Areas of expertise')),
                ('languages', models.JSONField(default=list, help_text='Languages spoken')),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.DurationField(blank=True, null=True)),
                ('client_satisfaction_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_requests_handled', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_concurrent_clients', models.PositiveIntegerField(default=20)),
                ('working_hours', models.JSONField(default=dict, help_text='Weekly working schedule')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConciergeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=15)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_approval', 'Pending Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='submitted', max_length=20)),
                ('preferred_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('location_preferences', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('client_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('client_feedback', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='concierge.conciergeagent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='concierge.conciergeservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConciergeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('client_preference', 'Client Preference'), ('follow_up', 'Follow-up Required'), ('escalation', 'Escalation'), ('achievement', 'Client Achievement'), ('concern', 'Concern'), ('recommendation', 'Recommendation')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Only visible to concierge team')),
                ('requires_action', models.BooleanField(default=False)),
                ('action_due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='concierge.conciergeagent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_notes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='concierge.conciergerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConciergeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('appointment_type', models.CharField(choices=[('specialist_consultation', 'Specialist Consultation'), ('wellness_session', 'Wellness Session'), ('health_screening', 'Health Screening'), ('fitness_assessment', 'Fitness Assessment'), ('nutrition_consultation', 'Nutrition Consultation'), ('lifestyle_planning', 'Lifestyle Planning'), ('follow_up', 'Follow-up Session')], max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('scheduled_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_virtual', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('preparation_instructions', models.TextField(blank=True)),
                ('post_appointment_notes', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_appointments', to='concierge.conciergeagent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_appointments', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concierge_appointments', to='specialists.specialist')),
                ('wellness_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concierge_appointments', to='wellness_plans.wellnessplan')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='concierge.conciergerequest')),
            ],
        ),
    ]
