# Generated by Django 5.0 on 2025-12-01 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fitness', 'Fitness & Training'), ('nutrition', 'Nutrition & Dietetics'), ('longevity', 'Longevity & Anti-aging'), ('mental_health', 'Mental Health & Wellness'), ('physiotherapy', 'Physiotherapy & Recovery'), ('alternative', 'Alternative Medicine'), ('coaching', 'Life & Performance Coaching')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Specialist Categories',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Dr., Prof., etc.', max_length=100)),
                ('professional_summary', models.TextField()),
                ('years_experience', models.PositiveIntegerField()),
                ('tier', models.CharField(choices=[('premium', 'Premium'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='premium', max_length=20)),
                ('certifications', models.TextField(help_text='List of certifications and qualifications')),
                ('education', models.TextField(help_text='Educational background')),
                ('specializations', models.TextField(help_text='Areas of specialization')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consultation_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_hours', models.JSONField(default=dict, help_text='Weekly availability schedule')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_accepting_clients', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='specialists', to='specialists.specialistcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='specialists.specialist')),
            ],
            options={
                'unique_together': {('specialist', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='SpecialistReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('professionalism', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('expertise', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('communication', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('results', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='specialists.specialist')),
            ],
            options={
                'unique_together': {('specialist', 'client')},
            },
        ),
    ]
