# Generated by Django 5.0 on 2025-12-01 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('plan_type', models.CharField(choices=[('comprehensive', 'Comprehensive Wellness'), ('fitness', 'Fitness Focus'), ('nutrition', 'Nutrition Focus'), ('mental_wellness', 'Mental Wellness'), ('longevity', 'Longevity & Anti-aging'), ('recovery', 'Recovery & Rehabilitation'), ('performance', 'Performance Optimization')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('duration_weeks', models.PositiveIntegerField()),
                ('sessions_per_week', models.PositiveIntegerField()),
                ('estimated_time_per_session', models.PositiveIntegerField(help_text='Minutes per session')),
                ('primary_goals', models.JSONField(default=list, help_text='List of primary goals')),
                ('target_metrics', models.JSONField(default=dict, help_text='Target metrics and KPIs')),
                ('success_criteria', models.TextField()),
                ('ai_model_version', models.CharField(default='v1.0', max_length=50)),
                ('personalization_factors', models.JSONField(default=dict)),
                ('adaptation_rules', models.JSONField(default=dict)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_week', models.PositiveIntegerField(default=1)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialists', models.ManyToManyField(blank=True, related_name='assigned_plans', to='specialists.specialist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('module_type', models.CharField(choices=[('fitness', 'Fitness Training'), ('nutrition', 'Nutrition Plan'), ('mindfulness', 'Mindfulness & Meditation'), ('recovery', 'Recovery & Rest'), ('lifestyle', 'Lifestyle Changes'), ('supplementation', 'Supplementation'), ('monitoring', 'Health Monitoring')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('instructions', models.TextField()),
                ('resources', models.JSONField(default=list, help_text='Links, videos, documents')),
                ('exercises', models.JSONField(default=list, help_text='List of exercises or activities')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='wellness_plans.wellnessplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('week_number', models.PositiveIntegerField()),
                ('session_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('instructions', models.TextField()),
                ('exercises', models.JSONField(default=list)),
                ('materials_needed', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wellness_plans.planmodule')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wellness_plans.wellnessplan')),
            ],
            options={
                'ordering': ['week_number', 'session_number'],
                'unique_together': {('plan', 'week_number', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='PlanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('week_number', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('muscle_mass', models.FloatField(blank=True, null=True)),
                ('strength_metrics', models.JSONField(blank=True, default=dict)),
                ('endurance_metrics', models.JSONField(blank=True, default=dict)),
                ('flexibility_metrics', models.JSONField(blank=True, default=dict)),
                ('energy_level', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('sleep_quality', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('stress_level', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('mood_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='wellness_plans.wellnessplan')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('plan', 'date')},
            },
        ),
    ]
